package org.fundaciobit.pluginsib.validatecertificate.afirmacxf.validarcertificadoapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.12.redhat-00001
 * 2021-06-29T12:19:26.963+02:00
 * Generated source version: 3.2.12.redhat-00001
 *
 */
@WebService(targetNamespace = "http://afirmaws/services/ValidarCertificado", name = "ValidacionWS")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ValidacionWS {

    @WebMethod(operationName = "ValidarCertificado")
    @WebResult(name = "ValidarCertificadoReturn", targetNamespace = "http://afirmaws/services/ValidarCertificado", partName = "ValidarCertificadoReturn")
    public java.lang.String validarCertificado(
        @WebParam(partName = "parametrosIn", name = "parametrosIn")
        java.lang.String parametrosIn
    );
}
