package org.fundaciobit.pluginsib.validatecertificate.afirmacxf.validarcertificadoapi;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.12.redhat-00001
 * 2021-06-29T12:19:26.992+02:00
 * Generated source version: 3.2.12.redhat-00001
 *
 */
@WebServiceClient(name = "ValidacionService",
                  wsdlLocation = "http://des-afirma.redsara.es/afirmaws/services/ValidarCertificado?wsdl",
                  targetNamespace = "http://afirmaws/services/ValidarCertificado")
public class ValidacionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://afirmaws/services/ValidarCertificado", "ValidacionService");
    public final static QName ValidarCertificado = new QName("http://afirmaws/services/ValidarCertificado", "ValidarCertificado");
    static {
        URL url = null;
        try {
            url = new URL("http://des-afirma.redsara.es/afirmaws/services/ValidarCertificado?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ValidacionService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://des-afirma.redsara.es/afirmaws/services/ValidarCertificado?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ValidacionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidacionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidacionService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ValidacionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ValidacionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ValidacionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ValidacionWS
     */
    @WebEndpoint(name = "ValidarCertificado")
    public ValidacionWS getValidarCertificado() {
        return super.getPort(ValidarCertificado, ValidacionWS.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidacionWS
     */
    @WebEndpoint(name = "ValidarCertificado")
    public ValidacionWS getValidarCertificado(WebServiceFeature... features) {
        return super.getPort(ValidarCertificado, ValidacionWS.class, features);
    }

}
