<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.fundaciobit.pluginsib.validatecertificate</groupId>
        <artifactId>pluginsib-validatecertificate</artifactId>
        <version>3.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>pluginsib-validatecertificate-afirmacxf</artifactId>
    <packaging>jar</packaging>
    <name>PluginsIB - Validate Certificate - @FirmaCXF</name>

    <dependencies>
        <dependency>
            <groupId>org.fundaciobit.pluginsib.validatecertificate</groupId>
            <artifactId>pluginsib-validatecertificate-api</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.utils</groupId>
            <artifactId>pluginsib-utils-cxf</artifactId>
            <version>3.0.0-SNAPSHOT</version>
        </dependency>


        <dependency>
            <groupId>org.jboss.spec.javax.xml.ws</groupId>
            <artifactId>jboss-jaxws-api_2.3_spec</artifactId>
        </dependency>

        <dependency>
            <groupId>org.jboss.spec.javax.xml.bind</groupId>
            <artifactId>jboss-jaxb-api_2.3_spec</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.jws</groupId>
            <artifactId>jsr181-api</artifactId>
        </dependency>


        <dependency>
            <groupId>org.jboss.spec.javax.annotation</groupId>
            <artifactId>jboss-annotations-api_1.3_spec</artifactId>
        </dependency>

        <dependency>
            <groupId>javax.activation</groupId>
            <artifactId>activation</artifactId>
        </dependency>


        <dependency>
            <groupId>com.sun.xml.messaging.saaj</groupId>
            <artifactId>saaj-impl</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>xml-apis</groupId>
                    <artifactId>xml-apis</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
        </dependency>


        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.7.22</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.fundaciobit.pluginsib.validatecertificate</groupId>
            <artifactId>pluginsib-validatecertificate-api</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

    </dependencies>


</project>
